dist: xenial
language: python
python: 3.7

install:
  - pip install -r requirements.txt

# Build steps
#  - do a basic test, defaulting to use "config.xml"
script:
  - cd tests
# test with default config.xml
  - python ../xml2jupyter.py
  - if [[ `diff user_params.py user_params_baseline_default.py` ]]; then >&2 echo "Fail"; exit 1; fi


notifications:
  email:
    recipients:
      - randy.heiland@gmail.com
    on_success: always # default: change  (always, never)
    on_failure: always # default: always
